### ISSUE TITLE
File generation after TARGET/SEARCH

### ISSUE THREAD

**Issue by lovelesh** [lovelesh/epanet-src#17]
@AmitSharma1094 @jindalsumit1991 

We need to modify the following files:
- Solution file should be divided into TANKS file and VALVES file
- Separate VALVE JOB file
- TARGET output file should also be 2 different files with TANK and VALVE values

**Comment by jindalsumit1991** [comment]
Let's meet tomorrow and discuss all the enhancements/issues. I think we can complete the changes by tomorrow.
